model:
  name: xgboost
  build_params:
    model_type: xgboost
    halt_model: False
    num_trees: 50
    objective: reg:squarederror
    step_size: 0.3
    device: cpu
    batch_size: 128
    gamma: 0
    scale_data: True
    max_bin: 256
  saver:
    filename: models/boost/moab/xgboost_model
  sweep:
    run: False
    search_algorithm: bayesian
    num_trials: 3
    scoring_func: r2
