model:
  name: xgboost
  build_params:
    model_type: xgboost
    fit_separate: False
    halt_model: False
    num_trees: 50
    objective: reg:squarederror
    step_size: 0.3
    device: cpu
    batch_size: 128
    gamma: 0
    scale_data: True
    max_bin: 256
  saver:
    filename: models/boost/moab/xgboost_model
  sweep:
    run: True
    search_algorithm: random
    num_trials: 3
    scoring_func: r2
    params:
      estimator__max_depth: [1, 3, 5, 10]
      estimator__gamma: [0, 0.5, 1, 5]
      estimator__subsample: [0.1, 0.5, 1]
